name: Update gh-pages

on:
  push:	
    branches:	
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: mkdir build
      - run: echo "# Hello World\nvia Pandoc" > input.md
      - uses: maxheld83/pandoc@v2
        with:
          args: "--standalone --output=build/index.html input.md"
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@2.0.3
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN_PAGES }}
          FOLDER: build
